### ISSUE TITLE
fpga server timeout recovery raises KeyError on 'executionCounter'

### ISSUE THREAD

**Issue by DanielSank** [martinisgroup/servers#135]
This is happening because the ADC class doesn't set `executionCounter` in the readback data.
I'm gunna just make it gracefully handle the case where `executionCounter` is not available.

Future work should implement the execution counter on any boards which support it!
I think this isn't implemented properly now out of laziness (probably laziness of past Dan).

**Comment by jwenner** [comment]
1. I believe this is equivalent (but stated better than) #99.
   1. @pomalley, I believe you had a fix that you said was implemented in the jump table branch. What was it?

**Comment by DanielSank** [comment]
I already fixed this. PR incoming.

**Comment by pomalley** [comment]
Question: I had "fixed" this in the JT branch by changing the ADC process readback function for build 7--specifically, I renamed the key `trigCount` to `executionCounter` because I thought it was a typo/bug. Is it in fact the case that the ADC build 7 reports the number of triggers, not executions, and thus my fix was incorrect?

**Comment by DanielSank** [comment]
I think you did the right thing, Peter. Can we close?

**Comment by pomalley** [comment]
Sure.
