### ISSUE TITLE
What is a DacRunner and why do I need one?

### ISSUE THREAD

**Issue by pomalley** [martinisgroup/servers#37]
I thought we were almost there with the jump table stuff, and then I realized I have no idea how `run_sequence` actually works. So now I'm wondering how much of the DacRunner stuff is going to need to be changed for the JT. Are there any gotchas here I should be aware of? (For DacRunners or run_sequence as a whole or anything else.)

**Comment by DanielSank** [comment]
The DacRunner is essentially storage of sequence data (SRAM, memory, jump table). The runner has  reference to an instance of one of the FPGA classes. That FPGA instance represents the _physical_ device, and the runner represents one sequence's idea of what that physical device should do.

Each context talking to the FPGA server stores its sequence data (SRAM, etc) on the context object. When it comes time to actually run, that data is transferred to a runner. The runner is responsible for making packets to send to the direct ethernet server which is why it needs to know information about the sequence. It makes these packets by sending the configuration info into it's FPGA instance's packet construction methods. Those packets are then sent to the direct ethernet server.
