### ISSUE TITLE
Set up build system for qubit sequencer

### ISSUE THREAD

**Issue by maffoo** [martinisgroup/servers#41]
Right now, the qubit sequencer source lives here, and we also package up the server as an executable jar and commit the built jar to the repo as well. We should have a real build system that can build this in a reproducible way. I suggest we use [sbt](http://www.scala-sbt.org/) for this.

**Comment by pomalley** [comment]
I don't have any experience with java build systems--is sbt better than Maven (which is something I've heard of ;-)?

Also, is it worth doing something official with the javadoc? I use it sometimes when I'm re-remembering how the sequencer works, but I don't know if it's worth version-controlling since it's auto-generated anyway.
